### ISSUE TITLE
Code output

### ISSUE THREAD

**Issue by matthewdavis2985** [matthewdavis2985/Oyster-Data-Checks#12]
Modify code so that the output of knit goes into the /output folder, instead of the /code folder

**Comment by matthewdavis2985** [comment]
Also need to make it so that name includes date and does not overwrite or conflict with existing outputs

**Comment by matthewdavis2985** [comment]
tried adding yaml code and knitr code to do this, but wouldn't work on knit. I reverted my changes. May come back to this or delete this issue. HTML outputs are currently ignored, so working output copies may work best here, and final, PDF copies can be saved in /outputs

YAML
`output_dir: "/outputs"
output_file: "RCRT.html"`

R
```r output_dir <- "path/to/your/output/directory" 
output_filename <- paste0(output_dir, "/output_", format(Sys.Date(), "%Y%m%d"), ".html")
knitr::opts_knit$set(output = output_filename)`

**Comment by E-Levine** [comment]
> tried adding yaml code and knitr code to do this, but wouldn't work on knit. I reverted my changes. May come back to this or delete this issue. HTML outputs are currently ignored, so working output copies may work best here, and final, PDF copies can be saved in /outputs
> 
> YAML `output_dir: "/outputs" output_file: "RCRT.html"`
> 
> R
> 
> ```r
> output_filename <- paste0(output_dir, "/output_", format(Sys.Date(), "%Y%m%d"), ".html")
> knitr::opts_knit$set(output = output_filename)`
> ```

The behavior of knit has to be changed to include the date in the file name by writing a function. Adding the following to your YAML header should do the trick:

knit: (function(inputFile, encoding) {rmarkdown::render(input = inputFile, encoding = encoding, output_file = paste0(substr(inputFile, 1, nchar(inputFile)-4), "_", Sys.Date(), '.html')) })

If you want a specific format of date rather than the default %Y-%m-%d, then use "format(Sys.Date(), [desired format])" instead of just "Sys.Date()".

**Comment by matthewdavis2985** [comment]
Decided not to do. Output is fine where it is and is included in .gitignore
